### ISSUE TITLE
Linter no longer works with CoffeeScript 1.11.0

### ISSUE THREAD

**Issue by zmillman** [srgraham/coffeelint-callback-handle-error#2]
This commit https://github.com/jashkenas/coffeescript/commit/021d2e437630a60ef4ea53556c2f64cecb762b8c refactored how literals were represented - so the logic for matching `'Literal'` tokens no longer works.

It should be updated to handle `'IdentifierLiteral'` tokens (while probably still supporting `'Literal'` for backwards compatibility with pre-1.11.0 coffeescript).

**Comment by srgraham** [comment]
whoa, a coffeescript 2 release actually looks promising now.
I'll update the tests on these so they make more sense.
